// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 27 Apr 2021 14:18:31 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package arss

/*
#cgo pkg-config: fftw3
#include "util.h"
#include "image_io.h"
#include "sound_io.h"
#include "dsp.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
