// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 27 Apr 2021 14:18:31 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "util.h"
#include "image_io.h"
#include "sound_io.h"
#include "dsp.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

