// WARNING: This file has automatically been generated on Tue, 27 Apr 2021 14:26:54 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void fftw_write_char_func_do_not_use_me_c0889f19(char c, void* arg1) {
	fftwWriteCharFuncDoNotUseMeC0889F19(c, arg1);
}

int fftw_read_char_func_do_not_use_me_b89d953(void* arg0) {
	return fftwReadCharFuncDoNotUseMeB89D953(arg0);
}

int fftw_read_char_func_fddf6e16(void* arg0) {
	return fftwReadCharFuncFDDF6E16(arg0);
}

void fftw_write_char_func_1727d7df(char c, void* arg1) {
	fftwWriteCharFunc1727D7DF(c, arg1);
}

int fftwf_read_char_func_b387922c(void* arg0) {
	return fftwfReadCharFuncB387922C(arg0);
}

void fftwf_write_char_func_d1655691(char c, void* arg1) {
	fftwfWriteCharFuncD1655691(c, arg1);
}

int fftwl_read_char_func_47342800(void* arg0) {
	return fftwlReadCharFunc47342800(arg0);
}

void fftwl_write_char_func_e34989c8(char c, void* arg1) {
	fftwlWriteCharFuncE34989C8(c, arg1);
}

