GENERATOR: 
  PackageName: arss
  PackageDescription: "Package arss provides Go bindings for the Analysis & Resynthesis Sound Spectrograph library, written by Michel Rouzic."
  PkgConfigOpts: [fftw3]
  Includes: ["util.h", "image_io.h", "sound_io.h", "dsp.h"]
  Options:
    SafeStrings: true

PARSER: 
  IncludePaths: []
  SourcesPaths: ["util.h", "image_io.h", "sound_io.h", "dsp.h"]
  Defines:
    __builtin_va_start: {}
    __builtin_va_end: {}
    __has_include_next(x): 1
    _POSIX_C_SOURCE: 1

TRANSLATOR: 
  ConstCharIsString: true
  ConstUCharIsString: false
  Rules: 
    global: 
      - {transform: lower}
      - {action: accept, from: "in_"}
      - {action: accept, from: "out_"}
      - {action: accept, from: "_in"}
      - {action: accept, from: "_out"}
      - {transform: export}
    type: 
      - {action: replace, from: "_t$"}
    private:
      - {transform: unexport}
    post-global: 
      - {action: replace, from: _$}
      - {load: snakecase}