// WARNING: This file has automatically been generated on Tue, 27 Apr 2021 14:34:23 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package arss provides Go bindings for the Analysis & Resynthesis Sound Spectrograph library, written by Michel Rouzic.
*/
package arss
