// WARNING: This file has automatically been generated on Tue, 27 Apr 2021 14:34:23 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package arss

/*
#cgo pkg-config: fftw3
#include "util.h"
#include "image_io.h"
#include "sound_io.h"
#include "dsp.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// _DarwinNlItem type as declared in include/_types.h:40
type _DarwinNlItem int32

// _DarwinWctrans type as declared in include/_types.h:41
type _DarwinWctrans int32

// _DarwinWctype type as declared in include/_types.h:43
type _DarwinWctype uint32

// _DarwinBlkcnt type as declared in sys/_types.h:55
type _DarwinBlkcnt int64

// _DarwinBlksize type as declared in sys/_types.h:56
type _DarwinBlksize int32

// _DarwinDev type as declared in sys/_types.h:57
type _DarwinDev int32

// _DarwinFsblkcnt type as declared in sys/_types.h:58
type _DarwinFsblkcnt uint32

// _DarwinFsfilcnt type as declared in sys/_types.h:59
type _DarwinFsfilcnt uint32

// _DarwinGid type as declared in sys/_types.h:60
type _DarwinGid uint32

// _DarwinId type as declared in sys/_types.h:61
type _DarwinId uint32

// _DarwinIno64 type as declared in sys/_types.h:62
type _DarwinIno64 uint64

// _DarwinIno type as declared in sys/_types.h:64
type _DarwinIno uint64

// _DarwinMachPortName type as declared in sys/_types.h:68
type _DarwinMachPortName uint32

// _DarwinMachPort type as declared in sys/_types.h:69
type _DarwinMachPort uint32

// _DarwinMode type as declared in sys/_types.h:70
type _DarwinMode uint16

// _DarwinOff type as declared in sys/_types.h:71
type _DarwinOff int64

// _DarwinPid type as declared in sys/_types.h:72
type _DarwinPid int32

// _DarwinSigset type as declared in sys/_types.h:73
type _DarwinSigset uint32

// _DarwinSuseconds type as declared in sys/_types.h:74
type _DarwinSuseconds int32

// _DarwinUid type as declared in sys/_types.h:75
type _DarwinUid uint32

// _DarwinUseconds type as declared in sys/_types.h:76
type _DarwinUseconds uint32

// _DarwinUuid type as declared in sys/_types.h:77
type _DarwinUuid [16]byte

// _DarwinUuidString type as declared in sys/_types.h:78
type _DarwinUuidString [37]byte

// _Int8 type as declared in i386/_types.h:37
type _Int8 byte

// _Int16 type as declared in i386/_types.h:42
type _Int16 int16

// _Int32 type as declared in i386/_types.h:44
type _Int32 int32

// _Int64 type as declared in i386/_types.h:46
type _Int64 int64

// _DarwinIntptr type as declared in i386/_types.h:49
type _DarwinIntptr int32

// _DarwinNatural type as declared in i386/_types.h:50
type _DarwinNatural uint32

// _DarwinCtRune type as declared in i386/_types.h:70
type _DarwinCtRune int32

// _DarwinMbstate as declared in i386/_types.h:81
const sizeof_DarwinMbstate = unsafe.Sizeof(C.__mbstate_t{})

type _DarwinMbstate [sizeof_DarwinMbstate]byte

// _DarwinPtrdiff type as declared in i386/_types.h:84
type _DarwinPtrdiff int32

// _DarwinSize type as declared in i386/_types.h:92
type _DarwinSize uint32

// _DarwinVaList type as declared in i386/_types.h:98
type _DarwinVaList unsafe.Pointer

// _DarwinWchar type as declared in i386/_types.h:104
type _DarwinWchar int32

// _DarwinRune type as declared in i386/_types.h:109
type _DarwinRune int32

// _DarwinWint type as declared in i386/_types.h:112
type _DarwinWint int32

// _DarwinClock type as declared in i386/_types.h:117
type _DarwinClock uint32

// _DarwinSocklen type as declared in i386/_types.h:118
type _DarwinSocklen uint32

// _DarwinSsize type as declared in i386/_types.h:119
type _DarwinSsize int32

// _DarwinTime type as declared in i386/_types.h:120
type _DarwinTime int32

// _DarwinPthreadAttr as declared in _pthread/_pthread_types.h:109
type _DarwinPthreadAttr struct {
	_Sig           int32
	_Opaque        [56]byte
	ref8274dce0    *C.__darwin_pthread_attr_t
	allocs8274dce0 interface{}
}

// _DarwinPthreadCond as declared in _pthread/_pthread_types.h:110
type _DarwinPthreadCond struct {
	_Sig           int32
	_Opaque        [40]byte
	refff83b341    *C.__darwin_pthread_cond_t
	allocsff83b341 interface{}
}

// _DarwinPthreadCondattr as declared in _pthread/_pthread_types.h:111
type _DarwinPthreadCondattr struct {
	_Sig           int32
	_Opaque        [8]byte
	ref1f4b9d9e    *C.__darwin_pthread_condattr_t
	allocs1f4b9d9e interface{}
}

// _DarwinPthreadKey type as declared in _pthread/_pthread_types.h:112
type _DarwinPthreadKey uint32

// _DarwinPthreadMutex as declared in _pthread/_pthread_types.h:113
type _DarwinPthreadMutex struct {
	_Sig           int32
	_Opaque        [56]byte
	refafa2b7f7    *C.__darwin_pthread_mutex_t
	allocsafa2b7f7 interface{}
}

// _DarwinPthreadMutexattr as declared in _pthread/_pthread_types.h:114
type _DarwinPthreadMutexattr struct {
	_Sig           int32
	_Opaque        [8]byte
	refc7af6013    *C.__darwin_pthread_mutexattr_t
	allocsc7af6013 interface{}
}

// _DarwinPthreadOnce as declared in _pthread/_pthread_types.h:115
type _DarwinPthreadOnce struct {
	_Sig           int32
	_Opaque        [8]byte
	ref4689e860    *C.__darwin_pthread_once_t
	allocs4689e860 interface{}
}

// _DarwinPthreadRwlock as declared in _pthread/_pthread_types.h:116
type _DarwinPthreadRwlock struct {
	_Sig           int32
	_Opaque        [192]byte
	refe32755e2    *C.__darwin_pthread_rwlock_t
	allocse32755e2 interface{}
}

// _DarwinPthreadRwlockattr as declared in _pthread/_pthread_types.h:117
type _DarwinPthreadRwlockattr struct {
	_Sig           int32
	_Opaque        [16]byte
	ref3390a2c5    *C.__darwin_pthread_rwlockattr_t
	allocs3390a2c5 interface{}
}

// _DarwinPthread as declared in _pthread/_pthread_types.h:118
type _DarwinPthread struct {
	_Sig           int32
	_CleanupStack  []_DarwinPthreadHandlerRec
	_Opaque        [8176]byte
	ref2cab891a    *C.__darwin_pthread_t
	allocs2cab891a interface{}
}

// UInt8 type as declared in _types/_u_int8_t.h:30
type UInt8 byte

// UInt16 type as declared in _types/_u_int16_t.h:30
type UInt16 uint16

// UInt32 type as declared in _types/_u_int32_t.h:30
type UInt32 uint32

// UInt64 type as declared in _types/_u_int64_t.h:30
type UInt64 uint64

// _DarwinFpControl as declared in i386/_structs.h:117
type _DarwinFpControl struct {
	_Invalid       uint16
	_Denorm        uint16
	_Zdiv          uint16
	_Ovrfl         uint16
	_Undfl         uint16
	_Precis        uint16
	Field6         int32
	_Pc            uint16
	_Rc            uint16
	Field9         int32
	Field10        int32
	refc3b35bbb    *C.__darwin_fp_control_t
	allocsc3b35bbb interface{}
}

// _DarwinFpStatus as declared in i386/_structs.h:167
type _DarwinFpStatus struct {
	_Invalid       uint16
	_Denorm        uint16
	_Zdiv          uint16
	_Ovrfl         uint16
	_Undfl         uint16
	_Precis        uint16
	_Stkflt        uint16
	_Errsumm       uint16
	_C0            uint16
	_C1            uint16
	_C2            uint16
	_Tos           uint16
	_C3            uint16
	_Busy          uint16
	ref88b7dfb8    *C.__darwin_fp_status_t
	allocs88b7dfb8 interface{}
}

// _DarwinI386Avx512State as declared in i386/_structs.h:364
type _DarwinI386Avx512State struct {
	_FpuReserved   [2]int32
	_FpuFcw        _DarwinFpControl
	_FpuFsw        _DarwinFpStatus
	_FpuFtw        byte
	_FpuRsrv1      byte
	_FpuFop        uint16
	_FpuIp         uint32
	_FpuCs         uint16
	_FpuRsrv2      uint16
	_FpuDp         uint32
	_FpuDs         uint16
	_FpuRsrv3      uint16
	_FpuMxcsr      uint32
	_FpuMxcsrmask  uint32
	_FpuStmm0      _DarwinMmstReg
	_FpuStmm1      _DarwinMmstReg
	_FpuStmm2      _DarwinMmstReg
	_FpuStmm3      _DarwinMmstReg
	_FpuStmm4      _DarwinMmstReg
	_FpuStmm5      _DarwinMmstReg
	_FpuStmm6      _DarwinMmstReg
	_FpuStmm7      _DarwinMmstReg
	_FpuXmm0       _DarwinXmmReg
	_FpuXmm1       _DarwinXmmReg
	_FpuXmm2       _DarwinXmmReg
	_FpuXmm3       _DarwinXmmReg
	_FpuXmm4       _DarwinXmmReg
	_FpuXmm5       _DarwinXmmReg
	_FpuXmm6       _DarwinXmmReg
	_FpuXmm7       _DarwinXmmReg
	_FpuRsrv4      [224]byte
	_FpuReserved1  int32
	_AvxReserved1  [64]byte
	_FpuYmmh0      _DarwinXmmReg
	_FpuYmmh1      _DarwinXmmReg
	_FpuYmmh2      _DarwinXmmReg
	_FpuYmmh3      _DarwinXmmReg
	_FpuYmmh4      _DarwinXmmReg
	_FpuYmmh5      _DarwinXmmReg
	_FpuYmmh6      _DarwinXmmReg
	_FpuYmmh7      _DarwinXmmReg
	_FpuK0         _DarwinOpmaskReg
	_FpuK1         _DarwinOpmaskReg
	_FpuK2         _DarwinOpmaskReg
	_FpuK3         _DarwinOpmaskReg
	_FpuK4         _DarwinOpmaskReg
	_FpuK5         _DarwinOpmaskReg
	_FpuK6         _DarwinOpmaskReg
	_FpuK7         _DarwinOpmaskReg
	_FpuZmmh0      _DarwinYmmReg
	_FpuZmmh1      _DarwinYmmReg
	_FpuZmmh2      _DarwinYmmReg
	_FpuZmmh3      _DarwinYmmReg
	_FpuZmmh4      _DarwinYmmReg
	_FpuZmmh5      _DarwinYmmReg
	_FpuZmmh6      _DarwinYmmReg
	_FpuZmmh7      _DarwinYmmReg
	ref5db8cb9e    *C.struct___darwin_i386_avx512_state
	allocs5db8cb9e interface{}
}

// _DarwinI386AvxState as declared in i386/_structs.h:318
type _DarwinI386AvxState struct {
	_FpuReserved   [2]int32
	_FpuFcw        _DarwinFpControl
	_FpuFsw        _DarwinFpStatus
	_FpuFtw        byte
	_FpuRsrv1      byte
	_FpuFop        uint16
	_FpuIp         uint32
	_FpuCs         uint16
	_FpuRsrv2      uint16
	_FpuDp         uint32
	_FpuDs         uint16
	_FpuRsrv3      uint16
	_FpuMxcsr      uint32
	_FpuMxcsrmask  uint32
	_FpuStmm0      _DarwinMmstReg
	_FpuStmm1      _DarwinMmstReg
	_FpuStmm2      _DarwinMmstReg
	_FpuStmm3      _DarwinMmstReg
	_FpuStmm4      _DarwinMmstReg
	_FpuStmm5      _DarwinMmstReg
	_FpuStmm6      _DarwinMmstReg
	_FpuStmm7      _DarwinMmstReg
	_FpuXmm0       _DarwinXmmReg
	_FpuXmm1       _DarwinXmmReg
	_FpuXmm2       _DarwinXmmReg
	_FpuXmm3       _DarwinXmmReg
	_FpuXmm4       _DarwinXmmReg
	_FpuXmm5       _DarwinXmmReg
	_FpuXmm6       _DarwinXmmReg
	_FpuXmm7       _DarwinXmmReg
	_FpuRsrv4      [224]byte
	_FpuReserved1  int32
	_AvxReserved1  [64]byte
	_FpuYmmh0      _DarwinXmmReg
	_FpuYmmh1      _DarwinXmmReg
	_FpuYmmh2      _DarwinXmmReg
	_FpuYmmh3      _DarwinXmmReg
	_FpuYmmh4      _DarwinXmmReg
	_FpuYmmh5      _DarwinXmmReg
	_FpuYmmh6      _DarwinXmmReg
	_FpuYmmh7      _DarwinXmmReg
	ref3806343e    *C.struct___darwin_i386_avx_state
	allocs3806343e interface{}
}

// _DarwinI386ExceptionState as declared in i386/_structs.h:575
type _DarwinI386ExceptionState struct {
	_Trapno        uint16
	_Cpu           uint16
	_Err           uint32
	_Faultvaddr    uint32
	refa1b2e769    *C.struct___darwin_i386_exception_state
	allocsa1b2e769 interface{}
}

// _DarwinI386FloatState as declared in i386/_structs.h:281
type _DarwinI386FloatState struct {
	_FpuReserved   [2]int32
	_FpuFcw        _DarwinFpControl
	_FpuFsw        _DarwinFpStatus
	_FpuFtw        byte
	_FpuRsrv1      byte
	_FpuFop        uint16
	_FpuIp         uint32
	_FpuCs         uint16
	_FpuRsrv2      uint16
	_FpuDp         uint32
	_FpuDs         uint16
	_FpuRsrv3      uint16
	_FpuMxcsr      uint32
	_FpuMxcsrmask  uint32
	_FpuStmm0      _DarwinMmstReg
	_FpuStmm1      _DarwinMmstReg
	_FpuStmm2      _DarwinMmstReg
	_FpuStmm3      _DarwinMmstReg
	_FpuStmm4      _DarwinMmstReg
	_FpuStmm5      _DarwinMmstReg
	_FpuStmm6      _DarwinMmstReg
	_FpuStmm7      _DarwinMmstReg
	_FpuXmm0       _DarwinXmmReg
	_FpuXmm1       _DarwinXmmReg
	_FpuXmm2       _DarwinXmmReg
	_FpuXmm3       _DarwinXmmReg
	_FpuXmm4       _DarwinXmmReg
	_FpuXmm5       _DarwinXmmReg
	_FpuXmm6       _DarwinXmmReg
	_FpuXmm7       _DarwinXmmReg
	_FpuRsrv4      [224]byte
	_FpuReserved1  int32
	refa3972104    *C.struct___darwin_i386_float_state
	allocsa3972104 interface{}
}

// _DarwinI386ThreadState as declared in i386/_structs.h:46
type _DarwinI386ThreadState struct {
	_Eax           uint32
	_Ebx           uint32
	_Ecx           uint32
	_Edx           uint32
	_Edi           uint32
	_Esi           uint32
	_Ebp           uint32
	_Esp           uint32
	_Ss            uint32
	_Eflags        uint32
	_Eip           uint32
	_Cs            uint32
	_Ds            uint32
	_Es            uint32
	_Fs            uint32
	_Gs            uint32
	ref45d0404b    *C.struct___darwin_i386_thread_state
	allocs45d0404b interface{}
}

// _DarwinMcontext32 as declared in i386/_mcontext.h:39
type _DarwinMcontext32 struct {
	_Es            _DarwinI386ExceptionState
	_Ss            _DarwinI386ThreadState
	_Fs            _DarwinI386FloatState
	ref5566d785    *C.struct___darwin_mcontext32
	allocs5566d785 interface{}
}

// Mcontext as declared in i386/_mcontext.h:204
type Mcontext struct {
	_Es            _DarwinX86ExceptionState64
	_Ss            _DarwinX86ThreadState64
	_Fs            _DarwinX86FloatState64
	ref1645c3e1    *C.mcontext_t
	allocs1645c3e1 interface{}
}

// _DarwinMcontext64Full as declared in i386/_mcontext.h:105
type _DarwinMcontext64Full struct {
	_Es            _DarwinX86ExceptionState64
	_Ss            _DarwinX86ThreadFullState64
	_Fs            _DarwinX86FloatState64
	ref7028c840    *C.struct___darwin_mcontext64_full
	allocs7028c840 interface{}
}

// _DarwinMcontextAvx32 as declared in i386/_mcontext.h:47
type _DarwinMcontextAvx32 struct {
	_Es            _DarwinI386ExceptionState
	_Ss            _DarwinI386ThreadState
	_Fs            _DarwinI386AvxState
	ref732c5bd8    *C.struct___darwin_mcontext_avx32
	allocs732c5bd8 interface{}
}

// _DarwinMcontextAvx51232 as declared in i386/_mcontext.h:56
type _DarwinMcontextAvx51232 struct {
	_Es            _DarwinI386ExceptionState
	_Ss            _DarwinI386ThreadState
	_Fs            _DarwinI386Avx512State
	refc2f730c9    *C.struct___darwin_mcontext_avx512_32
	allocsc2f730c9 interface{}
}

// _DarwinMcontextAvx51264 as declared in i386/_mcontext.h:130
type _DarwinMcontextAvx51264 struct {
	_Es            _DarwinX86ExceptionState64
	_Ss            _DarwinX86ThreadState64
	_Fs            _DarwinX86Avx512State64
	ref56e361b9    *C.struct___darwin_mcontext_avx512_64
	allocs56e361b9 interface{}
}

// _DarwinMcontextAvx51264Full as declared in i386/_mcontext.h:138
type _DarwinMcontextAvx51264Full struct {
	_Es            _DarwinX86ExceptionState64
	_Ss            _DarwinX86ThreadFullState64
	_Fs            _DarwinX86Avx512State64
	ref6452ca93    *C.struct___darwin_mcontext_avx512_64_full
	allocs6452ca93 interface{}
}

// _DarwinMcontextAvx64 as declared in i386/_mcontext.h:113
type _DarwinMcontextAvx64 struct {
	_Es            _DarwinX86ExceptionState64
	_Ss            _DarwinX86ThreadState64
	_Fs            _DarwinX86AvxState64
	refe7380aa8    *C.struct___darwin_mcontext_avx64
	allocse7380aa8 interface{}
}

// _DarwinMcontextAvx64Full as declared in i386/_mcontext.h:121
type _DarwinMcontextAvx64Full struct {
	_Es            _DarwinX86ExceptionState64
	_Ss            _DarwinX86ThreadFullState64
	_Fs            _DarwinX86AvxState64
	refa9f7418b    *C.struct___darwin_mcontext_avx64_full
	allocsa9f7418b interface{}
}

// _DarwinMmstReg as declared in i386/_structs.h:194
type _DarwinMmstReg struct {
	_MmstReg       [10]byte
	_MmstRsrv      [6]byte
	ref89d6b8d7    *C.struct___darwin_mmst_reg
	allocs89d6b8d7 interface{}
}

// _DarwinOpmaskReg as declared in i386/_structs.h:259
type _DarwinOpmaskReg struct {
	_OpmaskReg     [8]byte
	ref1c0e34dd    *C.struct___darwin_opmask_reg
	allocs1c0e34dd interface{}
}

// _DarwinPthreadHandlerRec as declared in _pthread/_pthread_types.h:57
type _DarwinPthreadHandlerRec struct {
	_Routine      *func(arg0 unsafe.Pointer)
	_Arg          unsafe.Pointer
	_Next         []_DarwinPthreadHandlerRec
	refdc59d4e    *C.struct___darwin_pthread_handler_rec
	allocsdc59d4e interface{}
}

// Stack as declared in _types/_sigaltstack.h:48
type Stack struct {
	SsSp           unsafe.Pointer
	SsSize         _DarwinSize
	SsFlags        int32
	ref73578c70    *C.stack_t
	allocs73578c70 interface{}
}

// Ucontext as declared in _types/_ucontext.h:57
type Ucontext struct {
	UcOnstack      int32
	UcSigmask      _DarwinSigset
	UcStack        _DarwinSigaltstack
	UcLink         []_DarwinUcontext
	UcMcsize       _DarwinSize
	UcMcontext     _DarwinMcontext64
	ref121f15cf    *C.ucontext_t
	allocs121f15cf interface{}
}

// _DarwinX86Avx512State64 as declared in i386/_structs.h:913
type _DarwinX86Avx512State64 struct {
	_FpuReserved   [2]int32
	_FpuFcw        _DarwinFpControl
	_FpuFsw        _DarwinFpStatus
	_FpuFtw        byte
	_FpuRsrv1      byte
	_FpuFop        uint16
	_FpuIp         uint32
	_FpuCs         uint16
	_FpuRsrv2      uint16
	_FpuDp         uint32
	_FpuDs         uint16
	_FpuRsrv3      uint16
	_FpuMxcsr      uint32
	_FpuMxcsrmask  uint32
	_FpuStmm0      _DarwinMmstReg
	_FpuStmm1      _DarwinMmstReg
	_FpuStmm2      _DarwinMmstReg
	_FpuStmm3      _DarwinMmstReg
	_FpuStmm4      _DarwinMmstReg
	_FpuStmm5      _DarwinMmstReg
	_FpuStmm6      _DarwinMmstReg
	_FpuStmm7      _DarwinMmstReg
	_FpuXmm0       _DarwinXmmReg
	_FpuXmm1       _DarwinXmmReg
	_FpuXmm2       _DarwinXmmReg
	_FpuXmm3       _DarwinXmmReg
	_FpuXmm4       _DarwinXmmReg
	_FpuXmm5       _DarwinXmmReg
	_FpuXmm6       _DarwinXmmReg
	_FpuXmm7       _DarwinXmmReg
	_FpuXmm8       _DarwinXmmReg
	_FpuXmm9       _DarwinXmmReg
	_FpuXmm10      _DarwinXmmReg
	_FpuXmm11      _DarwinXmmReg
	_FpuXmm12      _DarwinXmmReg
	_FpuXmm13      _DarwinXmmReg
	_FpuXmm14      _DarwinXmmReg
	_FpuXmm15      _DarwinXmmReg
	_FpuRsrv4      [96]byte
	_FpuReserved1  int32
	_AvxReserved1  [64]byte
	_FpuYmmh0      _DarwinXmmReg
	_FpuYmmh1      _DarwinXmmReg
	_FpuYmmh2      _DarwinXmmReg
	_FpuYmmh3      _DarwinXmmReg
	_FpuYmmh4      _DarwinXmmReg
	_FpuYmmh5      _DarwinXmmReg
	_FpuYmmh6      _DarwinXmmReg
	_FpuYmmh7      _DarwinXmmReg
	_FpuYmmh8      _DarwinXmmReg
	_FpuYmmh9      _DarwinXmmReg
	_FpuYmmh10     _DarwinXmmReg
	_FpuYmmh11     _DarwinXmmReg
	_FpuYmmh12     _DarwinXmmReg
	_FpuYmmh13     _DarwinXmmReg
	_FpuYmmh14     _DarwinXmmReg
	_FpuYmmh15     _DarwinXmmReg
	_FpuK0         _DarwinOpmaskReg
	_FpuK1         _DarwinOpmaskReg
	_FpuK2         _DarwinOpmaskReg
	_FpuK3         _DarwinOpmaskReg
	_FpuK4         _DarwinOpmaskReg
	_FpuK5         _DarwinOpmaskReg
	_FpuK6         _DarwinOpmaskReg
	_FpuK7         _DarwinOpmaskReg
	_FpuZmmh0      _DarwinYmmReg
	_FpuZmmh1      _DarwinYmmReg
	_FpuZmmh2      _DarwinYmmReg
	_FpuZmmh3      _DarwinYmmReg
	_FpuZmmh4      _DarwinYmmReg
	_FpuZmmh5      _DarwinYmmReg
	_FpuZmmh6      _DarwinYmmReg
	_FpuZmmh7      _DarwinYmmReg
	_FpuZmmh8      _DarwinYmmReg
	_FpuZmmh9      _DarwinYmmReg
	_FpuZmmh10     _DarwinYmmReg
	_FpuZmmh11     _DarwinYmmReg
	_FpuZmmh12     _DarwinYmmReg
	_FpuZmmh13     _DarwinYmmReg
	_FpuZmmh14     _DarwinYmmReg
	_FpuZmmh15     _DarwinYmmReg
	_FpuZmm16      _DarwinZmmReg
	_FpuZmm17      _DarwinZmmReg
	_FpuZmm18      _DarwinZmmReg
	_FpuZmm19      _DarwinZmmReg
	_FpuZmm20      _DarwinZmmReg
	_FpuZmm21      _DarwinZmmReg
	_FpuZmm22      _DarwinZmmReg
	_FpuZmm23      _DarwinZmmReg
	_FpuZmm24      _DarwinZmmReg
	_FpuZmm25      _DarwinZmmReg
	_FpuZmm26      _DarwinZmmReg
	_FpuZmm27      _DarwinZmmReg
	_FpuZmm28      _DarwinZmmReg
	_FpuZmm29      _DarwinZmmReg
	_FpuZmm30      _DarwinZmmReg
	_FpuZmm31      _DarwinZmmReg
	reff418433e    *C.struct___darwin_x86_avx512_state64
	allocsf418433e interface{}
}

// _DarwinX86AvxState64 as declared in i386/_structs.h:845
type _DarwinX86AvxState64 struct {
	_FpuReserved   [2]int32
	_FpuFcw        _DarwinFpControl
	_FpuFsw        _DarwinFpStatus
	_FpuFtw        byte
	_FpuRsrv1      byte
	_FpuFop        uint16
	_FpuIp         uint32
	_FpuCs         uint16
	_FpuRsrv2      uint16
	_FpuDp         uint32
	_FpuDs         uint16
	_FpuRsrv3      uint16
	_FpuMxcsr      uint32
	_FpuMxcsrmask  uint32
	_FpuStmm0      _DarwinMmstReg
	_FpuStmm1      _DarwinMmstReg
	_FpuStmm2      _DarwinMmstReg
	_FpuStmm3      _DarwinMmstReg
	_FpuStmm4      _DarwinMmstReg
	_FpuStmm5      _DarwinMmstReg
	_FpuStmm6      _DarwinMmstReg
	_FpuStmm7      _DarwinMmstReg
	_FpuXmm0       _DarwinXmmReg
	_FpuXmm1       _DarwinXmmReg
	_FpuXmm2       _DarwinXmmReg
	_FpuXmm3       _DarwinXmmReg
	_FpuXmm4       _DarwinXmmReg
	_FpuXmm5       _DarwinXmmReg
	_FpuXmm6       _DarwinXmmReg
	_FpuXmm7       _DarwinXmmReg
	_FpuXmm8       _DarwinXmmReg
	_FpuXmm9       _DarwinXmmReg
	_FpuXmm10      _DarwinXmmReg
	_FpuXmm11      _DarwinXmmReg
	_FpuXmm12      _DarwinXmmReg
	_FpuXmm13      _DarwinXmmReg
	_FpuXmm14      _DarwinXmmReg
	_FpuXmm15      _DarwinXmmReg
	_FpuRsrv4      [96]byte
	_FpuReserved1  int32
	_AvxReserved1  [64]byte
	_FpuYmmh0      _DarwinXmmReg
	_FpuYmmh1      _DarwinXmmReg
	_FpuYmmh2      _DarwinXmmReg
	_FpuYmmh3      _DarwinXmmReg
	_FpuYmmh4      _DarwinXmmReg
	_FpuYmmh5      _DarwinXmmReg
	_FpuYmmh6      _DarwinXmmReg
	_FpuYmmh7      _DarwinXmmReg
	_FpuYmmh8      _DarwinXmmReg
	_FpuYmmh9      _DarwinXmmReg
	_FpuYmmh10     _DarwinXmmReg
	_FpuYmmh11     _DarwinXmmReg
	_FpuYmmh12     _DarwinXmmReg
	_FpuYmmh13     _DarwinXmmReg
	_FpuYmmh14     _DarwinXmmReg
	_FpuYmmh15     _DarwinXmmReg
	ref1de1744d    *C.struct___darwin_x86_avx_state64
	allocs1de1744d interface{}
}

// _DarwinX86CpmuState64 as declared in i386/_structs.h:1300
type _DarwinX86CpmuState64 struct {
	_Ctrs         [16]uint64
	refd1cd1f0    *C.struct___darwin_x86_cpmu_state64
	allocsd1cd1f0 interface{}
}

// _DarwinX86DebugState32 as declared in i386/_structs.h:595
type _DarwinX86DebugState32 struct {
	_Dr0           uint32
	_Dr1           uint32
	_Dr2           uint32
	_Dr3           uint32
	_Dr4           uint32
	_Dr5           uint32
	_Dr6           uint32
	_Dr7           uint32
	ref11c7aee1    *C.struct___darwin_x86_debug_state32
	allocs11c7aee1 interface{}
}

// _DarwinX86DebugState64 as declared in i386/_structs.h:1272
type _DarwinX86DebugState64 struct {
	_Dr0           uint64
	_Dr1           uint64
	_Dr2           uint64
	_Dr3           uint64
	_Dr4           uint64
	_Dr5           uint64
	_Dr6           uint64
	_Dr7           uint64
	ref85d3ff91    *C.struct___darwin_x86_debug_state64
	allocs85d3ff91 interface{}
}

// _DarwinX86ExceptionState64 as declared in i386/_structs.h:1252
type _DarwinX86ExceptionState64 struct {
	_Trapno        uint16
	_Cpu           uint16
	_Err           uint32
	_Faultvaddr    uint64
	refe6844d5e    *C.struct___darwin_x86_exception_state64
	allocse6844d5e interface{}
}

// _DarwinX86FloatState64 as declared in i386/_structs.h:794
type _DarwinX86FloatState64 struct {
	_FpuReserved  [2]int32
	_FpuFcw       _DarwinFpControl
	_FpuFsw       _DarwinFpStatus
	_FpuFtw       byte
	_FpuRsrv1     byte
	_FpuFop       uint16
	_FpuIp        uint32
	_FpuCs        uint16
	_FpuRsrv2     uint16
	_FpuDp        uint32
	_FpuDs        uint16
	_FpuRsrv3     uint16
	_FpuMxcsr     uint32
	_FpuMxcsrmask uint32
	_FpuStmm0     _DarwinMmstReg
	_FpuStmm1     _DarwinMmstReg
	_FpuStmm2     _DarwinMmstReg
	_FpuStmm3     _DarwinMmstReg
	_FpuStmm4     _DarwinMmstReg
	_FpuStmm5     _DarwinMmstReg
	_FpuStmm6     _DarwinMmstReg
	_FpuStmm7     _DarwinMmstReg
	_FpuXmm0      _DarwinXmmReg
	_FpuXmm1      _DarwinXmmReg
	_FpuXmm2      _DarwinXmmReg
	_FpuXmm3      _DarwinXmmReg
	_FpuXmm4      _DarwinXmmReg
	_FpuXmm5      _DarwinXmmReg
	_FpuXmm6      _DarwinXmmReg
	_FpuXmm7      _DarwinXmmReg
	_FpuXmm8      _DarwinXmmReg
	_FpuXmm9      _DarwinXmmReg
	_FpuXmm10     _DarwinXmmReg
	_FpuXmm11     _DarwinXmmReg
	_FpuXmm12     _DarwinXmmReg
	_FpuXmm13     _DarwinXmmReg
	_FpuXmm14     _DarwinXmmReg
	_FpuXmm15     _DarwinXmmReg
	_FpuRsrv4     [96]byte
	_FpuReserved1 int32
	ref8ba626a    *C.struct___darwin_x86_float_state64
	allocs8ba626a interface{}
}

// _DarwinX86ThreadFullState64 as declared in i386/_structs.h:771
type _DarwinX86ThreadFullState64 struct {
	_Ss64          _DarwinX86ThreadState64
	_Ds            uint64
	_Es            uint64
	_Ss            uint64
	_Gsbase        uint64
	ref9e1a6f92    *C.struct___darwin_x86_thread_full_state64
	allocs9e1a6f92 interface{}
}

// _DarwinX86ThreadState64 as declared in i386/_structs.h:713
type _DarwinX86ThreadState64 struct {
	_Rax           uint64
	_Rbx           uint64
	_Rcx           uint64
	_Rdx           uint64
	_Rdi           uint64
	_Rsi           uint64
	_Rbp           uint64
	_Rsp           uint64
	_R8            uint64
	_R9            uint64
	_R10           uint64
	_R11           uint64
	_R12           uint64
	_R13           uint64
	_R14           uint64
	_R15           uint64
	_Rip           uint64
	_Rflags        uint64
	_Cs            uint64
	_Fs            uint64
	_Gs            uint64
	ref723d30a4    *C.struct___darwin_x86_thread_state64
	allocs723d30a4 interface{}
}

// _DarwinXmmReg as declared in i386/_structs.h:213
type _DarwinXmmReg struct {
	_XmmReg        [16]byte
	ref4ce4c564    *C.struct___darwin_xmm_reg
	allocs4ce4c564 interface{}
}

// _DarwinYmmReg as declared in i386/_structs.h:229
type _DarwinYmmReg struct {
	_YmmReg        [32]byte
	refea93ced0    *C.struct___darwin_ymm_reg
	allocsea93ced0 interface{}
}

// _DarwinZmmReg as declared in i386/_structs.h:245
type _DarwinZmmReg struct {
	_ZmmReg        [64]byte
	refdb7bd44d    *C.struct___darwin_zmm_reg
	allocsdb7bd44d interface{}
}

// _X86InstructionState as declared in i386/_structs.h:608
type _X86InstructionState struct {
	_InsnStreamValidBytes int32
	_InsnOffset           int32
	_OutOfSynch           int32
	_InsnBytes            [2380]byte
	_InsnCacheline        [64]byte
	ref37c5b7fe           *C.struct___x86_instruction_state
	allocs37c5b7fe        interface{}
}

// _X86PageinState as declared in i386/_structs.h:702
type _X86PageinState struct {
	_PageinError   int32
	ref95432405    *C.struct___x86_pagein_state
	allocs95432405 interface{}
}
